var R=require("../../../../../../chunks/[turbopack]_runtime.js")("server/app/app/api/book/me/dashboard/route.js")
R.c("server/chunks/[root-of-the-server]__dca7d686._.js")
R.c("server/chunks/node_modules_next_6e1517ac._.js")
R.c("server/chunks/node_modules_@aws-sdk_client-dynamodb_ec54177a._.js")
R.c("server/chunks/node_modules_@aws-sdk_client-sfn_cefa5595._.js")
R.c("server/chunks/[root-of-the-server]__67991579._.js")
R.c("server/chunks/[root-of-the-server]__be505248._.js")
R.c("server/chunks/_next-internal_server_app_app_api_book_me_dashboard_route_actions_21402db7.js")
R.m("[project]/node_modules/next/dist/esm/build/templates/app-route.js { INNER_APP_ROUTE => \"[project]/app/app/api/book/me/dashboard/route.ts [app-route] (ecmascript)\" } [app-route] (ecmascript)")
module.exports=R.m("[project]/node_modules/next/dist/esm/build/templates/app-route.js { INNER_APP_ROUTE => \"[project]/app/app/api/book/me/dashboard/route.ts [app-route] (ecmascript)\" } [app-route] (ecmascript)").exports
