var R=require("../../../../../../chunks/[turbopack]_runtime.js")("server/app/app/api/book/me/badges/route.js")
R.c("server/chunks/[root-of-the-server]__2470ed7b._.js")
R.c("server/chunks/node_modules_next_1118b2a5._.js")
R.c("server/chunks/node_modules_@aws-sdk_client-dynamodb_ec54177a._.js")
R.c("server/chunks/node_modules_@aws-sdk_client-sfn_cefa5595._.js")
R.c("server/chunks/[root-of-the-server]__67991579._.js")
R.c("server/chunks/[root-of-the-server]__9dca83b3._.js")
R.c("server/chunks/_next-internal_server_app_app_api_book_me_badges_route_actions_3cf8c42f.js")
R.m("[project]/node_modules/next/dist/esm/build/templates/app-route.js { INNER_APP_ROUTE => \"[project]/app/app/api/book/me/badges/route.ts [app-route] (ecmascript)\" } [app-route] (ecmascript)")
module.exports=R.m("[project]/node_modules/next/dist/esm/build/templates/app-route.js { INNER_APP_ROUTE => \"[project]/app/app/api/book/me/badges/route.ts [app-route] (ecmascript)\" } [app-route] (ecmascript)").exports
