var R=require("../../../../../../chunks/[turbopack]_runtime.js")("server/app/app/api/book/me/saved/route.js")
R.c("server/chunks/[root-of-the-server]__376f182e._.js")
R.c("server/chunks/node_modules_next_11bf8bea._.js")
R.c("server/chunks/node_modules_@aws-sdk_client-dynamodb_ec54177a._.js")
R.c("server/chunks/node_modules_@aws-sdk_client-sfn_cefa5595._.js")
R.c("server/chunks/[root-of-the-server]__67991579._.js")
R.c("server/chunks/[root-of-the-server]__193cf88e._.js")
R.c("server/chunks/_next-internal_server_app_app_api_book_me_saved_route_actions_64078ba5.js")
R.m("[project]/node_modules/next/dist/esm/build/templates/app-route.js { INNER_APP_ROUTE => \"[project]/app/app/api/book/me/saved/route.ts [app-route] (ecmascript)\" } [app-route] (ecmascript)")
module.exports=R.m("[project]/node_modules/next/dist/esm/build/templates/app-route.js { INNER_APP_ROUTE => \"[project]/app/app/api/book/me/saved/route.ts [app-route] (ecmascript)\" } [app-route] (ecmascript)").exports
