// This file is generated automatically by Next.js
// Do not edit this file manually

type AppRoutes = "/" | "/app" | "/app/projects" | "/app/projects/[projectId]" | "/app/projects/[projectId]/fill/[fileId]" | "/book" | "/book/badges" | "/book/home" | "/book/library" | "/book/library/[bookId]" | "/book/library/[bookId]/chapter/[chapterId]" | "/book/profile" | "/book/progress" | "/book/saved" | "/book/settings" | "/book/workspace" | "/chapterflow" | "/dashboard" | "/projects/[slug]"
type AppRouteHandlerRoutes = "/api/quota" | "/app/api/admin/quotas" | "/app/api/admin/quotas/overrides" | "/app/api/auth/session" | "/app/api/book/admin/books/[bookId]/versions" | "/app/api/book/admin/books/[bookId]/versions/[version]/publish" | "/app/api/book/admin/books/upload-request" | "/app/api/book/admin/ingest/run" | "/app/api/book/admin/ingestions/[jobId]" | "/app/api/book/admin/users/[userId]/entitlements" | "/app/api/book/billing/checkout-session" | "/app/api/book/billing/portal-session" | "/app/api/book/billing/webhook" | "/app/api/book/books" | "/app/api/book/books/[bookId]" | "/app/api/book/books/[bookId]/chapters/[chapterNumber]" | "/app/api/book/books/[bookId]/chapters/[chapterNumber]/quiz" | "/app/api/book/me/badges" | "/app/api/book/me/books/[bookId]/chapters/[chapterNumber]/state" | "/app/api/book/me/books/[bookId]/start" | "/app/api/book/me/books/[bookId]/state" | "/app/api/book/me/dashboard" | "/app/api/book/me/entitlements" | "/app/api/book/me/profile" | "/app/api/book/me/progress" | "/app/api/book/me/progress/[bookId]" | "/app/api/book/me/quiz/[bookId]/[chapterNumber]/submit" | "/app/api/book/me/reading-sessions" | "/app/api/book/me/saved" | "/app/api/book/me/settings" | "/app/api/me" | "/app/api/me/stats" | "/app/api/projects" | "/app/api/projects/[projectId]" | "/app/api/projects/[projectId]/convert" | "/app/api/projects/[projectId]/files" | "/app/api/projects/[projectId]/files/[fileId]" | "/app/api/projects/[projectId]/files/[fileId]/download" | "/app/api/projects/[projectId]/files/filled/[fileId]/complete" | "/app/api/projects/[projectId]/files/filled/[fileId]/upload" | "/app/api/projects/[projectId]/files/filled/create" | "/app/api/projects/[projectId]/uploads" | "/app/api/projects/[projectId]/uploads/[uploadId]/complete" | "/auth/callback" | "/auth/login" | "/auth/logout" | "/auth/session" | "/test"
type PageRoutes = never
type LayoutRoutes = "/" | "/app" | "/app/projects" | "/app/projects/[projectId]" | "/book"
type RedirectRoutes = "/book/home"
type RewriteRoutes = never
type Routes = AppRoutes | PageRoutes | LayoutRoutes | RedirectRoutes | RewriteRoutes | AppRouteHandlerRoutes


interface ParamMap {
  "/": {}
  "/api/quota": {}
  "/app": {}
  "/app/api/admin/quotas": {}
  "/app/api/admin/quotas/overrides": {}
  "/app/api/auth/session": {}
  "/app/api/book/admin/books/[bookId]/versions": { "bookId": string; }
  "/app/api/book/admin/books/[bookId]/versions/[version]/publish": { "bookId": string; "version": string; }
  "/app/api/book/admin/books/upload-request": {}
  "/app/api/book/admin/ingest/run": {}
  "/app/api/book/admin/ingestions/[jobId]": { "jobId": string; }
  "/app/api/book/admin/users/[userId]/entitlements": { "userId": string; }
  "/app/api/book/billing/checkout-session": {}
  "/app/api/book/billing/portal-session": {}
  "/app/api/book/billing/webhook": {}
  "/app/api/book/books": {}
  "/app/api/book/books/[bookId]": { "bookId": string; }
  "/app/api/book/books/[bookId]/chapters/[chapterNumber]": { "bookId": string; "chapterNumber": string; }
  "/app/api/book/books/[bookId]/chapters/[chapterNumber]/quiz": { "bookId": string; "chapterNumber": string; }
  "/app/api/book/me/badges": {}
  "/app/api/book/me/books/[bookId]/chapters/[chapterNumber]/state": { "bookId": string; "chapterNumber": string; }
  "/app/api/book/me/books/[bookId]/start": { "bookId": string; }
  "/app/api/book/me/books/[bookId]/state": { "bookId": string; }
  "/app/api/book/me/dashboard": {}
  "/app/api/book/me/entitlements": {}
  "/app/api/book/me/profile": {}
  "/app/api/book/me/progress": {}
  "/app/api/book/me/progress/[bookId]": { "bookId": string; }
  "/app/api/book/me/quiz/[bookId]/[chapterNumber]/submit": { "bookId": string; "chapterNumber": string; }
  "/app/api/book/me/reading-sessions": {}
  "/app/api/book/me/saved": {}
  "/app/api/book/me/settings": {}
  "/app/api/me": {}
  "/app/api/me/stats": {}
  "/app/api/projects": {}
  "/app/api/projects/[projectId]": { "projectId": string; }
  "/app/api/projects/[projectId]/convert": { "projectId": string; }
  "/app/api/projects/[projectId]/files": { "projectId": string; }
  "/app/api/projects/[projectId]/files/[fileId]": { "projectId": string; "fileId": string; }
  "/app/api/projects/[projectId]/files/[fileId]/download": { "projectId": string; "fileId": string; }
  "/app/api/projects/[projectId]/files/filled/[fileId]/complete": { "projectId": string; "fileId": string; }
  "/app/api/projects/[projectId]/files/filled/[fileId]/upload": { "projectId": string; "fileId": string; }
  "/app/api/projects/[projectId]/files/filled/create": { "projectId": string; }
  "/app/api/projects/[projectId]/uploads": { "projectId": string; }
  "/app/api/projects/[projectId]/uploads/[uploadId]/complete": { "projectId": string; "uploadId": string; }
  "/app/projects": {}
  "/app/projects/[projectId]": { "projectId": string; }
  "/app/projects/[projectId]/fill/[fileId]": { "projectId": string; "fileId": string; }
  "/auth/callback": {}
  "/auth/login": {}
  "/auth/logout": {}
  "/auth/session": {}
  "/book": {}
  "/book/badges": {}
  "/book/home": {}
  "/book/library": {}
  "/book/library/[bookId]": { "bookId": string; }
  "/book/library/[bookId]/chapter/[chapterId]": { "bookId": string; "chapterId": string; }
  "/book/profile": {}
  "/book/progress": {}
  "/book/saved": {}
  "/book/settings": {}
  "/book/workspace": {}
  "/chapterflow": {}
  "/dashboard": {}
  "/projects/[slug]": { "slug": string; }
  "/test": {}
}


export type ParamsOf<Route extends Routes> = ParamMap[Route]

interface LayoutSlotMap {
  "/": never
  "/app": never
  "/app/projects": never
  "/app/projects/[projectId]": never
  "/book": never
}


export type { AppRoutes, PageRoutes, LayoutRoutes, RedirectRoutes, RewriteRoutes, ParamMap, AppRouteHandlerRoutes }

declare global {
  /**
   * Props for Next.js App Router page components
   * @example
   * ```tsx
   * export default function Page(props: PageProps<'/blog/[slug]'>) {
   *   const { slug } = await props.params
   *   return <div>Blog post: {slug}</div>
   * }
   * ```
   */
  interface PageProps<AppRoute extends AppRoutes> {
    params: Promise<ParamMap[AppRoute]>
    searchParams: Promise<Record<string, string | string[] | undefined>>
  }

  /**
   * Props for Next.js App Router layout components
   * @example
   * ```tsx
   * export default function Layout(props: LayoutProps<'/dashboard'>) {
   *   return <div>{props.children}</div>
   * }
   * ```
   */
  type LayoutProps<LayoutRoute extends LayoutRoutes> = {
    params: Promise<ParamMap[LayoutRoute]>
    children: React.ReactNode
  } & {
    [K in LayoutSlotMap[LayoutRoute]]: React.ReactNode
  }

  /**
   * Context for Next.js App Router route handlers
   * @example
   * ```tsx
   * export async function GET(request: NextRequest, context: RouteContext<'/api/users/[id]'>) {
   *   const { id } = await context.params
   *   return Response.json({ id })
   * }
   * ```
   */
  interface RouteContext<AppRouteHandlerRoute extends AppRouteHandlerRoutes> {
    params: Promise<ParamMap[AppRouteHandlerRoute]>
  }
}
