// This file is generated automatically by Next.js
// Do not edit this file manually
// This file validates that all pages and layouts export the correct types

import type { AppRoutes, LayoutRoutes, ParamMap, AppRouteHandlerRoutes } from "./routes.js"
import type { ResolvingMetadata, ResolvingViewport } from "next/types.js"
import type { NextRequest } from 'next/server.js'

type AppPageConfig<Route extends AppRoutes = AppRoutes> = {
  default: React.ComponentType<{ params: Promise<ParamMap[Route]> } & any> | ((props: { params: Promise<ParamMap[Route]> } & any) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type LayoutConfig<Route extends LayoutRoutes = LayoutRoutes> = {
  default: React.ComponentType<LayoutProps<Route>> | ((props: LayoutProps<Route>) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type RouteHandlerConfig<Route extends AppRouteHandlerRoutes = AppRouteHandlerRoutes> = {
  GET?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  POST?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PUT?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PATCH?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  DELETE?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  HEAD?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  OPTIONS?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
}


// Validate ../../../app/app/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/app">> = Specific
  const handler = {} as typeof import("../../../app/app/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/app/projects/[projectId]/fill/[fileId]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/app/projects/[projectId]/fill/[fileId]">> = Specific
  const handler = {} as typeof import("../../../app/app/projects/[projectId]/fill/[fileId]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/app/projects/[projectId]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/app/projects/[projectId]">> = Specific
  const handler = {} as typeof import("../../../app/app/projects/[projectId]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/app/projects/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/app/projects">> = Specific
  const handler = {} as typeof import("../../../app/app/projects/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/book/badges/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/book/badges">> = Specific
  const handler = {} as typeof import("../../../app/book/badges/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/book/home/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/book/home">> = Specific
  const handler = {} as typeof import("../../../app/book/home/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/book/library/[bookId]/chapter/[chapterId]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/book/library/[bookId]/chapter/[chapterId]">> = Specific
  const handler = {} as typeof import("../../../app/book/library/[bookId]/chapter/[chapterId]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/book/library/[bookId]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/book/library/[bookId]">> = Specific
  const handler = {} as typeof import("../../../app/book/library/[bookId]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/book/library/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/book/library">> = Specific
  const handler = {} as typeof import("../../../app/book/library/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/book/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/book">> = Specific
  const handler = {} as typeof import("../../../app/book/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/book/profile/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/book/profile">> = Specific
  const handler = {} as typeof import("../../../app/book/profile/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/book/progress/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/book/progress">> = Specific
  const handler = {} as typeof import("../../../app/book/progress/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/book/saved/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/book/saved">> = Specific
  const handler = {} as typeof import("../../../app/book/saved/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/book/settings/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/book/settings">> = Specific
  const handler = {} as typeof import("../../../app/book/settings/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/book/workspace/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/book/workspace">> = Specific
  const handler = {} as typeof import("../../../app/book/workspace/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/chapterflow/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/chapterflow">> = Specific
  const handler = {} as typeof import("../../../app/chapterflow/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/dashboard/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard">> = Specific
  const handler = {} as typeof import("../../../app/dashboard/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/">> = Specific
  const handler = {} as typeof import("../../../app/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/projects/[slug]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/projects/[slug]">> = Specific
  const handler = {} as typeof import("../../../app/projects/[slug]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/quota/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/quota">> = Specific
  const handler = {} as typeof import("../../../app/api/quota/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/app/api/admin/quotas/overrides/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/app/api/admin/quotas/overrides">> = Specific
  const handler = {} as typeof import("../../../app/app/api/admin/quotas/overrides/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/app/api/admin/quotas/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/app/api/admin/quotas">> = Specific
  const handler = {} as typeof import("../../../app/app/api/admin/quotas/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/app/api/auth/session/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/app/api/auth/session">> = Specific
  const handler = {} as typeof import("../../../app/app/api/auth/session/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/app/api/book/admin/books/[bookId]/versions/[version]/publish/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/app/api/book/admin/books/[bookId]/versions/[version]/publish">> = Specific
  const handler = {} as typeof import("../../../app/app/api/book/admin/books/[bookId]/versions/[version]/publish/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/app/api/book/admin/books/[bookId]/versions/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/app/api/book/admin/books/[bookId]/versions">> = Specific
  const handler = {} as typeof import("../../../app/app/api/book/admin/books/[bookId]/versions/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/app/api/book/admin/books/upload-request/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/app/api/book/admin/books/upload-request">> = Specific
  const handler = {} as typeof import("../../../app/app/api/book/admin/books/upload-request/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/app/api/book/admin/ingest/run/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/app/api/book/admin/ingest/run">> = Specific
  const handler = {} as typeof import("../../../app/app/api/book/admin/ingest/run/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/app/api/book/admin/ingestions/[jobId]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/app/api/book/admin/ingestions/[jobId]">> = Specific
  const handler = {} as typeof import("../../../app/app/api/book/admin/ingestions/[jobId]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/app/api/book/admin/users/[userId]/entitlements/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/app/api/book/admin/users/[userId]/entitlements">> = Specific
  const handler = {} as typeof import("../../../app/app/api/book/admin/users/[userId]/entitlements/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/app/api/book/billing/checkout-session/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/app/api/book/billing/checkout-session">> = Specific
  const handler = {} as typeof import("../../../app/app/api/book/billing/checkout-session/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/app/api/book/billing/portal-session/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/app/api/book/billing/portal-session">> = Specific
  const handler = {} as typeof import("../../../app/app/api/book/billing/portal-session/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/app/api/book/billing/webhook/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/app/api/book/billing/webhook">> = Specific
  const handler = {} as typeof import("../../../app/app/api/book/billing/webhook/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/app/api/book/books/[bookId]/chapters/[chapterNumber]/quiz/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/app/api/book/books/[bookId]/chapters/[chapterNumber]/quiz">> = Specific
  const handler = {} as typeof import("../../../app/app/api/book/books/[bookId]/chapters/[chapterNumber]/quiz/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/app/api/book/books/[bookId]/chapters/[chapterNumber]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/app/api/book/books/[bookId]/chapters/[chapterNumber]">> = Specific
  const handler = {} as typeof import("../../../app/app/api/book/books/[bookId]/chapters/[chapterNumber]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/app/api/book/books/[bookId]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/app/api/book/books/[bookId]">> = Specific
  const handler = {} as typeof import("../../../app/app/api/book/books/[bookId]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/app/api/book/books/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/app/api/book/books">> = Specific
  const handler = {} as typeof import("../../../app/app/api/book/books/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/app/api/book/me/badges/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/app/api/book/me/badges">> = Specific
  const handler = {} as typeof import("../../../app/app/api/book/me/badges/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/app/api/book/me/books/[bookId]/chapters/[chapterNumber]/state/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/app/api/book/me/books/[bookId]/chapters/[chapterNumber]/state">> = Specific
  const handler = {} as typeof import("../../../app/app/api/book/me/books/[bookId]/chapters/[chapterNumber]/state/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/app/api/book/me/books/[bookId]/start/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/app/api/book/me/books/[bookId]/start">> = Specific
  const handler = {} as typeof import("../../../app/app/api/book/me/books/[bookId]/start/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/app/api/book/me/books/[bookId]/state/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/app/api/book/me/books/[bookId]/state">> = Specific
  const handler = {} as typeof import("../../../app/app/api/book/me/books/[bookId]/state/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/app/api/book/me/dashboard/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/app/api/book/me/dashboard">> = Specific
  const handler = {} as typeof import("../../../app/app/api/book/me/dashboard/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/app/api/book/me/entitlements/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/app/api/book/me/entitlements">> = Specific
  const handler = {} as typeof import("../../../app/app/api/book/me/entitlements/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/app/api/book/me/profile/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/app/api/book/me/profile">> = Specific
  const handler = {} as typeof import("../../../app/app/api/book/me/profile/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/app/api/book/me/progress/[bookId]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/app/api/book/me/progress/[bookId]">> = Specific
  const handler = {} as typeof import("../../../app/app/api/book/me/progress/[bookId]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/app/api/book/me/progress/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/app/api/book/me/progress">> = Specific
  const handler = {} as typeof import("../../../app/app/api/book/me/progress/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/app/api/book/me/quiz/[bookId]/[chapterNumber]/submit/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/app/api/book/me/quiz/[bookId]/[chapterNumber]/submit">> = Specific
  const handler = {} as typeof import("../../../app/app/api/book/me/quiz/[bookId]/[chapterNumber]/submit/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/app/api/book/me/reading-sessions/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/app/api/book/me/reading-sessions">> = Specific
  const handler = {} as typeof import("../../../app/app/api/book/me/reading-sessions/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/app/api/book/me/saved/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/app/api/book/me/saved">> = Specific
  const handler = {} as typeof import("../../../app/app/api/book/me/saved/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/app/api/book/me/settings/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/app/api/book/me/settings">> = Specific
  const handler = {} as typeof import("../../../app/app/api/book/me/settings/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/app/api/me/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/app/api/me">> = Specific
  const handler = {} as typeof import("../../../app/app/api/me/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/app/api/me/stats/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/app/api/me/stats">> = Specific
  const handler = {} as typeof import("../../../app/app/api/me/stats/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/app/api/projects/[projectId]/convert/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/app/api/projects/[projectId]/convert">> = Specific
  const handler = {} as typeof import("../../../app/app/api/projects/[projectId]/convert/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/app/api/projects/[projectId]/files/[fileId]/download/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/app/api/projects/[projectId]/files/[fileId]/download">> = Specific
  const handler = {} as typeof import("../../../app/app/api/projects/[projectId]/files/[fileId]/download/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/app/api/projects/[projectId]/files/[fileId]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/app/api/projects/[projectId]/files/[fileId]">> = Specific
  const handler = {} as typeof import("../../../app/app/api/projects/[projectId]/files/[fileId]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/app/api/projects/[projectId]/files/filled/[fileId]/complete/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/app/api/projects/[projectId]/files/filled/[fileId]/complete">> = Specific
  const handler = {} as typeof import("../../../app/app/api/projects/[projectId]/files/filled/[fileId]/complete/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/app/api/projects/[projectId]/files/filled/[fileId]/upload/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/app/api/projects/[projectId]/files/filled/[fileId]/upload">> = Specific
  const handler = {} as typeof import("../../../app/app/api/projects/[projectId]/files/filled/[fileId]/upload/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/app/api/projects/[projectId]/files/filled/create/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/app/api/projects/[projectId]/files/filled/create">> = Specific
  const handler = {} as typeof import("../../../app/app/api/projects/[projectId]/files/filled/create/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/app/api/projects/[projectId]/files/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/app/api/projects/[projectId]/files">> = Specific
  const handler = {} as typeof import("../../../app/app/api/projects/[projectId]/files/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/app/api/projects/[projectId]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/app/api/projects/[projectId]">> = Specific
  const handler = {} as typeof import("../../../app/app/api/projects/[projectId]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/app/api/projects/[projectId]/uploads/[uploadId]/complete/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/app/api/projects/[projectId]/uploads/[uploadId]/complete">> = Specific
  const handler = {} as typeof import("../../../app/app/api/projects/[projectId]/uploads/[uploadId]/complete/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/app/api/projects/[projectId]/uploads/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/app/api/projects/[projectId]/uploads">> = Specific
  const handler = {} as typeof import("../../../app/app/api/projects/[projectId]/uploads/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/app/api/projects/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/app/api/projects">> = Specific
  const handler = {} as typeof import("../../../app/app/api/projects/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/auth/callback/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/auth/callback">> = Specific
  const handler = {} as typeof import("../../../app/auth/callback/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/auth/login/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/auth/login">> = Specific
  const handler = {} as typeof import("../../../app/auth/login/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/auth/logout/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/auth/logout">> = Specific
  const handler = {} as typeof import("../../../app/auth/logout/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/auth/session/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/auth/session">> = Specific
  const handler = {} as typeof import("../../../app/auth/session/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/test/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/test">> = Specific
  const handler = {} as typeof import("../../../app/test/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}





// Validate ../../../app/app/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/app">> = Specific
  const handler = {} as typeof import("../../../app/app/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/app/projects/[projectId]/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/app/projects/[projectId]">> = Specific
  const handler = {} as typeof import("../../../app/app/projects/[projectId]/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/app/projects/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/app/projects">> = Specific
  const handler = {} as typeof import("../../../app/app/projects/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/book/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/book">> = Specific
  const handler = {} as typeof import("../../../app/book/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/">> = Specific
  const handler = {} as typeof import("../../../app/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}
